### ISSUE TITLE
Wearing sharks is bad it hurts them

### ISSUE THREAD

**Issue by fouadmxp** [fou3fou3/crawler-test-server#1]
NONO

**Comment by CelestialCrafter** [comment]
issue: it ate everything else

**Comment by fouadmxp** [comment]
![image](https://github.com/fou3fou3/crawler-test-server/assets/108154224/84afd4d4-6b21-4294-a8ab-049a46502c80)

**Comment by fouadmxp** [comment]
done we found some good dresses
